[2021-04-29 14:26:35,191] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: tutorial_taskflow_api_etl_test.getKiwiStationData 2021-04-29T08:55:50.766216+00:00 [queued]>
[2021-04-29 14:26:35,196] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: tutorial_taskflow_api_etl_test.getKiwiStationData 2021-04-29T08:55:50.766216+00:00 [queued]>
[2021-04-29 14:26:35,196] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-29 14:26:35,196] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2021-04-29 14:26:35,196] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-29 14:26:35,203] {taskinstance.py:1089} INFO - Executing <Task(_PythonDecoratedOperator): getKiwiStationData> on 2021-04-29T08:55:50.766216+00:00
[2021-04-29 14:26:35,205] {standard_task_runner.py:52} INFO - Started process 34279 to run task
[2021-04-29 14:26:35,213] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'tutorial_taskflow_api_etl_test', 'getKiwiStationData', '2021-04-29T08:55:50.766216+00:00', '--job-id', '32', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/simple.py', '--cfg-path', '/var/folders/jz/p2j8d5xx3lq5qbv4lwz8kg100000gn/T/tmpc6xgea34', '--error-file', '/var/folders/jz/p2j8d5xx3lq5qbv4lwz8kg100000gn/T/tmplxm3uasz']
[2021-04-29 14:26:35,215] {standard_task_runner.py:77} INFO - Job 32: Subtask getKiwiStationData
[2021-04-29 14:26:40,243] {logging_mixin.py:104} INFO - Running <TaskInstance: tutorial_taskflow_api_etl_test.getKiwiStationData 2021-04-29T08:55:50.766216+00:00 [running]> on host Keshavs-MacBook-Pro.local
[2021-04-29 14:26:45,266] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=tutorial_taskflow_api_etl_test
AIRFLOW_CTX_TASK_ID=getKiwiStationData
AIRFLOW_CTX_EXECUTION_DATE=2021-04-29T08:55:50.766216+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-04-29T08:55:50.766216+00:00
[2021-04-29 14:26:46,074] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/operators/python.py", line 233, in execute
    return_value = self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/dags/simple.py", line 62, in getKiwiStationData
    k = k.json()
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2021-04-29 14:26:46,082] {taskinstance.py:1525} INFO - Marking task as FAILED. dag_id=tutorial_taskflow_api_etl_test, task_id=getKiwiStationData, execution_date=20210429T085550, start_date=20210429T085635, end_date=20210429T085646
[2021-04-29 14:26:46,127] {local_task_job.py:146} INFO - Task exited with return code 1
