[2021-05-06 11:16:23,900] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: tutorial_taskflow_api_etl_test_2.extract 2021-05-06T05:46:07.165306+00:00 [queued]>
[2021-05-06 11:16:23,905] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: tutorial_taskflow_api_etl_test_2.extract 2021-05-06T05:46:07.165306+00:00 [queued]>
[2021-05-06 11:16:23,905] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-06 11:16:23,905] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2021-05-06 11:16:23,906] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-06 11:16:23,911] {taskinstance.py:1089} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2021-05-06T05:46:07.165306+00:00
[2021-05-06 11:16:23,913] {standard_task_runner.py:52} INFO - Started process 96859 to run task
[2021-05-06 11:16:23,919] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'tutorial_taskflow_api_etl_test_2', 'extract', '2021-05-06T05:46:07.165306+00:00', '--job-id', '102', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/demo2.py', '--cfg-path', '/var/folders/jz/p2j8d5xx3lq5qbv4lwz8kg100000gn/T/tmp1892zp2g', '--error-file', '/var/folders/jz/p2j8d5xx3lq5qbv4lwz8kg100000gn/T/tmpwwj81ru1']
[2021-05-06 11:16:23,921] {standard_task_runner.py:77} INFO - Job 102: Subtask extract
[2021-05-06 11:16:28,947] {logging_mixin.py:104} INFO - Running <TaskInstance: tutorial_taskflow_api_etl_test_2.extract 2021-05-06T05:46:07.165306+00:00 [running]> on host Keshavs-MacBook-Pro.local
[2021-05-06 11:16:33,968] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=tutorial_taskflow_api_etl_test_2
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2021-05-06T05:46:07.165306+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-06T05:46:07.165306+00:00
[2021-05-06 11:16:33,970] {logging_mixin.py:104} INFO - {'provider': 'kiwi', 'priority': 2, 'isActive': False, 'stationSource': '', 'destinationSource': '', 'includeByStation': [], 'excludeByStation': [], 'includeByGeo': [], 'excludeByGeo': [], 'onFailure': True}
[2021-05-06 11:16:33,970] {logging_mixin.py:104} INFO - kiwi
[2021-05-06 11:16:34,761] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/operators/python.py", line 233, in execute
    return_value = self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/dags/demo2.py", line 58, in extract
    getKiwiStationData()
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/dags/demo2.py", line 97, in getKiwiStationData
    merged_list = json.load(open("allStation.json"))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2021-05-06 11:16:34,765] {taskinstance.py:1525} INFO - Marking task as FAILED. dag_id=tutorial_taskflow_api_etl_test_2, task_id=extract, execution_date=20210506T054607, start_date=20210506T054623, end_date=20210506T054634
[2021-05-06 11:16:34,812] {local_task_job.py:146} INFO - Task exited with return code 1
