[2021-05-05 14:06:39,932] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: tutorial_taskflow_api_etl_test.create_all_station_list 2021-05-05T08:35:56.388841+00:00 [queued]>
[2021-05-05 14:06:39,935] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: tutorial_taskflow_api_etl_test.create_all_station_list 2021-05-05T08:35:56.388841+00:00 [queued]>
[2021-05-05 14:06:39,935] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-05 14:06:39,935] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2021-05-05 14:06:39,935] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-05 14:06:39,940] {taskinstance.py:1089} INFO - Executing <Task(_PythonDecoratedOperator): create_all_station_list> on 2021-05-05T08:35:56.388841+00:00
[2021-05-05 14:06:39,942] {standard_task_runner.py:52} INFO - Started process 35193 to run task
[2021-05-05 14:06:39,947] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'tutorial_taskflow_api_etl_test', 'create_all_station_list', '2021-05-05T08:35:56.388841+00:00', '--job-id', '81', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/simple.py', '--cfg-path', '/var/folders/jz/p2j8d5xx3lq5qbv4lwz8kg100000gn/T/tmpq97o8nd9', '--error-file', '/var/folders/jz/p2j8d5xx3lq5qbv4lwz8kg100000gn/T/tmpmb33woof']
[2021-05-05 14:06:39,949] {standard_task_runner.py:77} INFO - Job 81: Subtask create_all_station_list
[2021-05-05 14:06:44,983] {logging_mixin.py:104} INFO - Running <TaskInstance: tutorial_taskflow_api_etl_test.create_all_station_list 2021-05-05T08:35:56.388841+00:00 [running]> on host Keshavs-MacBook-Pro.local
[2021-05-05 14:06:50,004] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=tutorial_taskflow_api_etl_test
AIRFLOW_CTX_TASK_ID=create_all_station_list
AIRFLOW_CTX_EXECUTION_DATE=2021-05-05T08:35:56.388841+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-05T08:35:56.388841+00:00
[2021-05-05 14:06:50,004] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/operators/python.py", line 233, in execute
    return_value = self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/dags/simple.py", line 129, in create_all_station_list
    res_list = json.load(open("allStation.json"))
FileNotFoundError: [Errno 2] No such file or directory: 'allStation.json'
[2021-05-05 14:06:50,007] {taskinstance.py:1525} INFO - Marking task as FAILED. dag_id=tutorial_taskflow_api_etl_test, task_id=create_all_station_list, execution_date=20210505T083556, start_date=20210505T083639, end_date=20210505T083650
[2021-05-05 14:06:50,030] {local_task_job.py:146} INFO - Task exited with return code 1
