[2021-04-29 22:53:53,044] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: tutorial_taskflow_api_etl_test.getKiwiStationData 2021-04-29T17:23:07.294633+00:00 [queued]>
[2021-04-29 22:53:53,049] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: tutorial_taskflow_api_etl_test.getKiwiStationData 2021-04-29T17:23:07.294633+00:00 [queued]>
[2021-04-29 22:53:53,049] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-29 22:53:53,049] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2021-04-29 22:53:53,049] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-29 22:53:53,056] {taskinstance.py:1089} INFO - Executing <Task(_PythonDecoratedOperator): getKiwiStationData> on 2021-04-29T17:23:07.294633+00:00
[2021-04-29 22:53:53,058] {standard_task_runner.py:52} INFO - Started process 16433 to run task
[2021-04-29 22:53:53,063] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'tutorial_taskflow_api_etl_test', 'getKiwiStationData', '2021-04-29T17:23:07.294633+00:00', '--job-id', '45', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/simple.py', '--cfg-path', '/var/folders/jz/p2j8d5xx3lq5qbv4lwz8kg100000gn/T/tmpueigxy_d', '--error-file', '/var/folders/jz/p2j8d5xx3lq5qbv4lwz8kg100000gn/T/tmpd1rv5o70']
[2021-04-29 22:53:53,065] {standard_task_runner.py:77} INFO - Job 45: Subtask getKiwiStationData
[2021-04-29 22:53:58,090] {logging_mixin.py:104} INFO - Running <TaskInstance: tutorial_taskflow_api_etl_test.getKiwiStationData 2021-04-29T17:23:07.294633+00:00 [running]> on host Keshavs-MacBook-Pro.local
[2021-04-29 22:54:03,110] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=tutorial_taskflow_api_etl_test
AIRFLOW_CTX_TASK_ID=getKiwiStationData
AIRFLOW_CTX_EXECUTION_DATE=2021-04-29T17:23:07.294633+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-04-29T17:23:07.294633+00:00
[2021-04-29 22:54:03,621] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/operators/python.py", line 233, in execute
    return_value = self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/dags/simple.py", line 77, in getKiwiStationData
    merged_list = json.load(f)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
AttributeError: 'dict' object has no attribute 'read'
[2021-04-29 22:54:03,623] {taskinstance.py:1525} INFO - Marking task as FAILED. dag_id=tutorial_taskflow_api_etl_test, task_id=getKiwiStationData, execution_date=20210429T172307, start_date=20210429T172353, end_date=20210429T172403
[2021-04-29 22:54:03,668] {local_task_job.py:146} INFO - Task exited with return code 1
