[2021-05-05 12:18:13,538] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: tutorial_taskflow_api_etl_test_http.http_test 2021-05-05T06:47:56.162918+00:00 [queued]>
[2021-05-05 12:18:13,543] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: tutorial_taskflow_api_etl_test_http.http_test 2021-05-05T06:47:56.162918+00:00 [queued]>
[2021-05-05 12:18:13,544] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-05 12:18:13,544] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2021-05-05 12:18:13,544] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-05 12:18:13,550] {taskinstance.py:1089} INFO - Executing <Task(_PythonDecoratedOperator): http_test> on 2021-05-05T06:47:56.162918+00:00
[2021-05-05 12:18:13,553] {standard_task_runner.py:52} INFO - Started process 26708 to run task
[2021-05-05 12:18:13,559] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'tutorial_taskflow_api_etl_test_http', 'http_test', '2021-05-05T06:47:56.162918+00:00', '--job-id', '64', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/api_call.py', '--cfg-path', '/var/folders/jz/p2j8d5xx3lq5qbv4lwz8kg100000gn/T/tmptagx9fjl', '--error-file', '/var/folders/jz/p2j8d5xx3lq5qbv4lwz8kg100000gn/T/tmpiu5v7dh5']
[2021-05-05 12:18:13,561] {standard_task_runner.py:77} INFO - Job 64: Subtask http_test
[2021-05-05 12:18:18,592] {logging_mixin.py:104} INFO - Running <TaskInstance: tutorial_taskflow_api_etl_test_http.http_test 2021-05-05T06:47:56.162918+00:00 [running]> on host Keshavs-MacBook-Pro.local
[2021-05-05 12:18:23,615] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=tutorial_taskflow_api_etl_test_http
AIRFLOW_CTX_TASK_ID=http_test
AIRFLOW_CTX_EXECUTION_DATE=2021-05-05T06:47:56.162918+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-05T06:47:56.162918+00:00
[2021-05-05 12:18:23,619] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/operators/python.py", line 233, in execute
    return_value = self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/dags/api_call.py", line 78, in http_test
    task_get_op_response_filter = SimpleHttpOperator(
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 89, in __call__
    obj: BaseOperator = type.__call__(cls, *args, **kwargs)
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 88, in __init__
    super().__init__(**kwargs)
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/utils/decorators.py", line 94, in wrapper
    result = func(*args, **kwargs)
  File "/Users/keshavsultania/Documents/airflow-tutorial/demo1/myenv/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 412, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_op_response_filter). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2021-05-05 12:18:23,624] {taskinstance.py:1525} INFO - Marking task as FAILED. dag_id=tutorial_taskflow_api_etl_test_http, task_id=http_test, execution_date=20210505T064756, start_date=20210505T064813, end_date=20210505T064823
[2021-05-05 12:18:23,655] {local_task_job.py:146} INFO - Task exited with return code 1
